baseURL      = "https://secunit.io/"
title        = "hello | secunit"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  homeSubtitle = "welcome, and stuff ..."

  disableReadOtherPosts = false

  enableSharingButtons = true
  
  description = "matthew evans' localhost"
  keywords = "homepage, blog"
  images = [""]

  [[params.social]]
    name = "github"
    url = "https://github.com/x86txt"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/mevanssecurity/"

  [[params.social]]
    name = "goodreads"
    url  = "https://www.goodreads.com/user/show/138025628-matthew"

  [params.footer]
    trademark = true
    rss = true
    copyright = true
    author = false

    topText = []
    bottomText = [
      "powered by <a href=\"https://pages.cloudflare.com/\">cloudflare pages</a> & <a href=\"https://github.com/\">github</a>",
      "<script async data-id=\"101423814\" src=\"//static.getclicky.com/js\"></script>",
      "<noscript><p><img alt=\"Clicky\" width=\"1\" height=\"1\" src=\"//in.getclicky.com/101423814ns.gif\" /></p></noscript>"
    ]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "my digital home"
    subtitle = "welcome, and stuff ..."
    keywords = "matthew evans, devsecops, devops, secops, aws, azure, cloud, engineer"
    copyright = '<a href="https://creativecommons.org/publicdomain/zero/1.0/" target="_blank" rel="noopener">CC0 1.0 Universal</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "hello | secunit"
      logoHomeLink = "/"

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "about"
    url        = "/about"
  [[menu.main]]
    identifier = "posts"
    name       = "posts"
    url        = "/posts"
  [[menu.main]]
    identifier = "devops"
    name       = "devops"
    url        = "/devops"
  [[menu.main]]
    identifier = "files"
    name       = "files"
    url        = "https://files.secunit.io/"
  [[menu.main]]
    identifier = "portfolio"
    name       = "my portfolio"
    url        = "https://portfolio.secunit.io/"
