baseURL      = "https://secunit.io/"
title        = "hello | secunit"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "welcome, and stuff ..."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = false
  
  # Show a global language switcher in the navigation bar
  # enableGlobalLanguageMenu = true

  # Metadata mostly used in document's head
  description = "matthew evans' localhost"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "my digital home"
    subtitle = "welcome, and stuff ..."
    keywords = "matthew evans, devsecops, devops, secops, aws, azure, cloud, engineer"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "hello | secunit"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "about"
    url        = "/about"
  [[menu.main]]
    identifier = "posts"
    name       = "posts"
    url        = "/posts"
  [[menu.main]]
    identifier = "monero"
    name       = "monero"
    url        = "/monero"
  [[menu.main]]
    identifier = "devops"
    name       = "devops"
    url        = "/devops"
  [[menu.main]]
    identifier = "misc"
    name       = "misc"
    url        = "/misc"
